# This file was generated by GoReleaser. DO NOT EDIT.
cask "flue" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "8400ba79031e5bcf9dc01724d056b907a1b731dedfae1fb14bf410b63a2a0bd9"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9dfc5d7c97ea0da2d4242f48eed6b662ca539990918c1fbf59cd082101f3cd34"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "228a7b1656967ff5afebaf85c4d108fec9f4f3171c2b1e245e4ee74d76984900"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "46289cfb7f46ddd3e5af63fcec5b21e7c4e31ed6d74d6a1367a192b173149021"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flue"
  desc "Your terminal, as a browser tab."
  homepage "https://flue.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flue"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flue"]
    end
  end

  # No zap stanza required

end
