# This file was generated by GoReleaser. DO NOT EDIT.
cask "flue" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "2959708b809af90beb44ca0233a7e2a932b4d72182d60bb527959fd31548820e"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d6d8452b7b331c1e0867d55452fd826d2177802df9ee945b5eb30af5aa10654"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "adcd5f84fc1fc3300b6465d4a85de59f9d50834f0f7303fe05055e2abe78b04a"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88152c33472a1b65108a93dfab53d77a7ac15d81c76835879fdbfe56828b0753"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flue"
  desc "Your terminal, as a browser tab."
  homepage "https://flue.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flue"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flue"]
    end
  end

  # No zap stanza required

end
