# This file was generated by GoReleaser. DO NOT EDIT.
cask "flue" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "a6c821a226385ece0dd2538f13c1f5bb5c31052b54dbb67aef9df468f28126e1"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "404d3e59a954a8b4850fa8ce79fef8c4ff46a23a840f608ec43559508da8873e"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95beeb4a9940a6f01f84b563f4344df36b87012d2fc9c7bf76a25499695fdbd6"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8300157e28c0758695a18b091df06e369ae9bd880254dd9be6dee4e0fe16fe03"
      url "https://github.com/karnstack/flue/releases/download/v#{version}/flue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flue"
  desc "Your terminal, as a browser tab."
  homepage "https://flue.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flue"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flue"]
    end
  end

  # No zap stanza required

end
